name: apod
description: "An app that showcases daily images from NASA's Astronomy Picture of the Day, offering users a captivating glimpse into the wonders of the cosmos."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.1.0
  google_fonts: ^6.2.1
  dio: ^5.4.1
  curl_logger_dio_interceptor: ^1.0.0
  flutter_riverpod: ^2.4.10
  loading_animation_widget: ^1.2.1
  cached_network_image: ^3.3.1
  flutter_animate: ^4.5.0
  photo_view: ^0.15.0
  persistent_header_adaptive: ^2.1.0
  intl: ^0.19.0
  share_plus: ^8.0.3
  flutter_cache_manager: ^3.3.1
  fluttertoast: ^8.2.4
  webview_flutter: ^4.7.0
  url_launcher: ^6.2.5
  snapping_page_scroll: ^3.1.0
  shared_preferences: ^2.2.3
  path_provider: ^2.1.3
  collection: ^1.18.0
  bot_toast: ^4.1.3
  animated_digit: ^3.2.3
  animated_flip_counter: ^0.3.4
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/
    - .env

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
